import Head from 'next/head';

import UserOne from "../components/demo/userOne.js";
import ContentOne from "../components/demo/contentOne";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{marginBottom: "5rem"}}>
          <UserOne />
        </div>

        <div>
          <ContentOne />
        </div>
      </main>

    </div>
  )
}
