import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

import UserOne from "../components/demo/userOne.js";
import ContentOne from "../components/demo/contentOne";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{marginBottom: "5rem"}}>
          <UserOne />
        </div>

        <div>
          <ContentOne />
        </div>
      </main>

    </div>
  )
}
